simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import login, logout
from simplemooc.accounts.views import register


app_name = 'accounts'
urlpatterns = [
    path('entrar/', login,{'template_name': 'accounts/login.html'}, name="login"),
    path('sair/', logout,{'next_page': 'core:index'}, name="logout"),
    path('cadastre-se/', register, name="register")
]

simplemooc/core/urls.py
from django.urls import path
from simplemooc.core.views import home, contact

app_name = 'core'
urlpatterns = [
    path('', home, name="home"),
    path('contact/', contact, name="contact"),
]

simplemooc/courses/urls.py
from django.urls import path
from simplemooc.courses.views import index, details

app_name = 'courses' # namespace em django 2
urlpatterns = [
    path('', index, name="index"),
    path('<slug:slug>/', details, name='details') # acredito que tenha sido melhor usar slug ao invés da id do curso.
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='cursos')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
from django.db import models

# Create your models here.

simplemooc/core/models.py
from django.db import models

# Create your models here.

simplemooc/courses/models.py
from django.db import models

class CourseManager(models.Manager):
    def search(self,query):
        return self.get_queryset().filter( # com o models.Q é possível fazer comtrole lógico nas consultas
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query)
        )


# Create your models here.
class Course(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Description Simples', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    start_date = models.DateField(
        'Data de Início', null=True, blank=True
    )
    image = models.ImageField(
        upload_to='courses/images', verbose_name='Imagem', null=True, blank=True
    )
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    Updated_at = models.DateTimeField(
        'Atualizado em', auto_now=True
    )

    objects = CourseManager()

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('courses:details',(),{'slug':self.slug})

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'
        ordering = ['-name']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

def dict_from_class(cls):
     return dict(
         (key, value)
         for (key, value) in cls.__dict__.items()
         if key not in _excluded_keys
         )

class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Já existe Usuário com Este E-mail')
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)

        user.email = self.cleaned_data['email']


        if commit:
            user.save()
        return user

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template

class ContactCourse(forms.Form):
    name = forms.CharField(label = 'Nome', max_length=100)
    email =  forms.EmailField(label = "E-mail")
    message = forms.CharField(
        label = 'Mensagens/Dúvida', widget=forms.Textarea
    )

    def send_email(self, course):
        subject = '[%s] Contato' % course # Título da menssagem, "assunto"
        context = { # tupla definida para implementar e menssagem
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }

        send_mail_template( # esta função irá enviar um email automático definido acima, muitas possibilidades.
            subject,
            'courses/contact_email.html',
            context,
            [settings.CONTACT_EMAIL]
        )

simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings

from .forms import RegisterForm
# Create your views here.

def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password = form.cleaned_data['password1']
            )
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {'form': form}
    return render(request, template_name, context)

simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,'home.html')

def contact(request):
    return render(request,'contact.html')

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404

from .models import Course
from .forms import ContactCourse

# Create your views here.
def index(request):
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    context = {
        'courses': courses
    }
    return render(request, template_name, context)

def details(request, slug):
    course = get_object_or_404(Course, slug=slug) # pk significa Primary Key
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_email(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['course'] = course
    context['form'] = form

    template_name = 'courses/details.html'
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{%url 'accounts:register'%}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock content %}

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock content %}

simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
    <div class="header">
        <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
            <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
            <ul>
                <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
                <li><a href="{% url 'courses:index' %}">Cursos</a></li>
                <li><a href="{% url 'core:contact' %}">Contato</a></li>
                {% if user.authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
    <div class="content">
      {% block content%}{% endblock %}
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

simplemooc/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

simplemooc/core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content%}

  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
      <div class="l-box">
        <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
        <p>Abaixo a lista  de cursos disponíveis na plataforma</p>
      </div>
    </div>
  </div>
  {% for course in courses %}
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
      <div class="l-box">
        <a href="{{course.get_absolute_url}}"><img src="{% if course.image %}{{ course.image.url }}{% else %}{% static 'img/img-padrao.png' %}{% endif %}" alt="{{ course.name }}"></a>
      </div>
    </div>
    <div class="pure-u-2-3">
      <div class="l-box">
        <h4 class="content-subhead"><a href="{{course.get_absolute_url}}" title="">{{ course.name }}</a></h4>
        {{course.description|linebreaks}}
      </div>
    </div>
  </div>
  {% empty %}
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
      <div class="l-box">
        <p>Nenhum curso está disponível na plataforma</p>
      </div>
    </div>
  </div>
  {% endfor %}

{% endblock %}